CREATE  TABLE Despesa (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  idUsuario INTEGER NOT NULL,
  idCategoria INTEGER NOT NULL,
  data DATETIME DEFAULT CURRENT_DATE,
  descricao TEXT,
  valor REAL NULL ,
  dataVencimento DATETIME NULL);